services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: codejam
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - codejam_net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/codejam
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    working_dir: /app
    ports:
      - "8080:8080"
    networks:
      - codejam_net
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app
    networks:
      - codejam_net
volumes:
  postgres_data:
networks:
  codejam_net:
    driver: bridge
